### ISSUE TITLE
How to find weights?

### ISSUE THREAD

**Issue by khursani8** [jaideep11061982/Stratified_sampler_fastai#1]
Based on this example
``` learn.call_back_fns.append(partial(Sampling_call_back,weights,len(learn.data.train_dl))```

I don't know what value for weights

**Comment by jaideep11061982** [comment]
it is based the distribution of the classes. So if you want to maintain equal number of samples for your classes or category in epoch you would pass [1,1,1,1,1]
so if batch size is 80  ratio of no of eg. would  be 20:20:20 like that you have to pass the ratio of number of examples in this param.
